"""empty message

Revision ID: 1d3d5e4e1bc1
Revises: 39bc5c9a2d52
Create Date: 2022-08-10 19:09:45.190354

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d3d5e4e1bc1'
down_revision = '39bc5c9a2d52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('type', sa.String(), nullable=True))
    op.drop_column('content', 'content_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('content_type', postgresql.ENUM('TEXT', 'IMAGELINK', 'AUDIOLINK', 'VIDEOLINK', name='contenttype'), autoincrement=False, nullable=True))
    op.drop_column('content', 'type')
    # ### end Alembic commands ###
