"""empty message

Revision ID: 46a5f6c74f19
Revises: 1d3d5e4e1bc1
Create Date: 2022-08-11 10:40:33.497115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a5f6c74f19'
down_revision = '1d3d5e4e1bc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('plan', sa.Column('created_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan', 'created_date')
    op.alter_column('content', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
