"""empty message

Revision ID: 83454dd01be8
Revises: e6b72552be9e
Create Date: 2022-07-27 16:27:38.733321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83454dd01be8'
down_revision = 'e6b72552be9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('plan_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idea', sa.String(), nullable=True),
    sa.Column('planner', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.drop_table('win')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('win',
    sa.Column('Win_id', sa.INTEGER(), server_default=sa.text('nextval(\'"win_Win_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('achivement', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('winner', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Win_id', name='win_pkey')
    )
    op.drop_table('plan')
    # ### end Alembic commands ###
