"""empty message

Revision ID: 98ed59606e49
Revises: 46a5f6c74f19
Create Date: 2022-08-13 10:57:47.648730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98ed59606e49'
down_revision = '46a5f6c74f19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan', 'completed_at')
    # ### end Alembic commands ###
